import type { Service } from "./types"

export const servicesData: Service[] = [
  {
    id: "reabilitacao-ombro",
    icon: "Dumbbell",
    title: "Reabilitação do Ombro",
    shortDescription: "Protocolos específicos para lesões do manguito rotador, tendinites e instabilidade.",
    fullDescription:
      "Especialização em reabilitação do complexo do ombro, uma das articulações mais complexas do corpo humano. Utilizo protocolos baseados em evidências científicas para tratamento de lesões do manguito rotador, tendinites, bursites, instabilidade glenoumeral e síndrome do impacto. O tratamento é individualizado e progressivo, focando na restauração completa da função e retorno seguro às atividades.",
    benefits: [
      "Recuperação completa de lesões do manguito rotador",
      "Eliminação de dores e limitações funcionais",
      "Restauração da amplitude de movimento completa",
      "Fortalecimento progressivo e seguro",
      "Prevenção de recidivas e novas lesões",
      "Retorno otimizado ao esporte e atividades diárias",
    ],
    techniques: [
      "Exercícios terapêuticos progressivos",
      "Liberação miofascial do complexo do ombro",
      "Mobilização articular glenoumeral e escapular",
      "Fortalecimento do manguito rotador",
      "Reeducação neuromuscular e proprioceptiva",
      "Terapia manual especializada",
    ],
    idealFor: [
      "Lesões do manguito rotador (parciais ou completas)",
      "Tendinite do supraespinhal ou bíceps",
      "Bursite subacromial",
      "Síndrome do impacto",
      "Instabilidade do ombro",
      "Pós-operatório de cirurgias do ombro",
      "Atletas de overhead (natação, vôlei, tênis)",
    ],
    duration: "60 minutos por sessão",
    color: "from-[#0d7377] to-[#14919b]",
    featured: true,
  },
  {
    id: "quiropraxia-esportiva",
    icon: "Activity",
    title: "Quiropraxia",
    shortDescription: "Ajustes quiropráticos especializados para otimizar função articular e desempenho atlético.",
    fullDescription:
      "A Quiropraxia é uma abordagem especializada que utiliza ajustes articulares precisos para otimizar a função biomecânica, melhorar a mobilidade e prevenir lesões em atletas. Com formação pelo Instituto HIB (120h), aplico técnicas avançadas de manipulação vertebral e articular para restaurar o alinhamento adequado e maximizar o desempenho atlético.",
    benefits: [
      "Melhora da mobilidade articular e amplitude de movimento",
      "Redução de dores musculoesqueléticas e tensões",
      "Otimização do desempenho atlético e funcional",
      "Prevenção de lesões por desequilíbrios biomecânicos",
      "Recuperação mais rápida entre treinos e competições",
      "Correção de padrões de movimento disfuncionais",
    ],
    techniques: [
      "Ajustes quiropráticos de alta velocidade e baixa amplitude",
      "Manipulação articular específica",
      "Mobilização vertebral e periférica",
      "Técnicas de liberação de tecidos moles",
      "Avaliação biomecânica completa",
    ],
    idealFor: [
      "Atletas de alto rendimento",
      "Praticantes de CrossFit e musculação",
      "Corredores e ciclistas",
      "Lutadores e praticantes de artes marciais",
      "Pessoas com dores crônicas na coluna",
      "Indivíduos buscando otimização de performance",
    ],
    duration: "45-60 minutos por sessão",
    color: "from-[#14919b] to-[#0d7377]",
  },
  {
    id: "fisioterapia-neurofuncional",
    icon: "Brain",
    title: "Fisioterapia Neurofuncional",
    shortDescription: "Reabilitação especializada para disfunções neurológicas e recuperação funcional.",
    fullDescription:
      "Especialização em Fisioterapia Neurofuncional pela Anhanguera Educacional (2024), focada na reabilitação de pacientes com disfunções neurológicas como AVC, lesões medulares, Parkinson, esclerose múltipla e outras condições neuromusculares. Utilizo técnicas avançadas de neuroplasticidade para promover a recuperação funcional máxima e melhorar a qualidade de vida.",
    benefits: [
      "Recuperação de movimentos e funções perdidas",
      "Melhora do equilíbrio e coordenação motora",
      "Redução da espasticidade muscular",
      "Ganho de independência nas atividades diárias",
      "Prevenção de complicações secundárias",
      "Estimulação da neuroplasticidade cerebral",
    ],
    techniques: [
      "Facilitação neuromuscular proprioceptiva (FNP)",
      "Conceito Bobath",
      "Treino de marcha e equilíbrio",
      "Exercícios neuromotores funcionais",
      "Estimulação sensorial e proprioceptiva",
      "Terapia de restrição induzida",
    ],
    idealFor: [
      "Pacientes pós-AVC (derrame)",
      "Lesões medulares",
      "Doença de Parkinson",
      "Esclerose múltipla",
      "Paralisia cerebral",
      "Neuropatias periféricas",
      "Síndrome de Guillain-Barré",
    ],
    duration: "60 minutos por sessão",
    color: "from-[#6366f1] to-[#8b5cf6]",
  },
  {
    id: "fisioterapia-ortopedica",
    icon: "Bone",
    title: "Fisioterapia Traumato-Ortopédica",
    shortDescription: "Tratamento de lesões musculoesqueléticas, fraturas e pós-operatórios.",
    fullDescription:
      "Especialização em Fisioterapia Traumato-Ortopédica pela Anhanguera Educacional (2025), focada no tratamento de lesões musculoesqueléticas, fraturas, entorses, luxações e reabilitação pós-operatória. Experiência em reabilitação de joelho, tornozelo, quadril, coluna e membros superiores, utilizando protocolos baseados em evidências para recuperação completa.",
    benefits: [
      "Recuperação acelerada de lesões e cirurgias",
      "Redução de dor e inflamação",
      "Restauração da amplitude de movimento",
      "Fortalecimento muscular progressivo",
      "Retorno seguro às atividades",
      "Prevenção de complicações pós-operatórias",
    ],
    techniques: [
      "Mobilização articular",
      "Exercícios terapêuticos progressivos",
      "Fortalecimento funcional",
      "Treino proprioceptivo",
      "Terapia manual ortopédica",
      "Crioterapia e termoterapia",
    ],
    idealFor: [
      "Pós-operatório de cirurgias ortopédicas",
      "Fraturas em consolidação",
      "Entorses e luxações",
      "Lesões ligamentares (LCA, LCM)",
      "Tendinites e bursites",
      "Dores na coluna vertebral",
      "Lesões meniscais",
    ],
    duration: "50-60 minutos por sessão",
    color: "from-[#f59e0b] to-[#d97706]",
  },
  {
    id: "dor-cronica-fibromialgia",
    icon: "Heart",
    title: "Dor Crônica e Fibromialgia",
    shortDescription: "Manejo especializado de síndromes dolorosas crônicas com abordagem humanizada.",
    fullDescription:
      "Curso de Fisioterapia na Dor Crônica e Fibromialgia pela Faculdade Focus (2024). Experiência prática com Grupo de Fibromialgia em Taperoá/BA, aplicando técnicas de educação em dor, exercícios terapêuticos, liberação miofascial e abordagens humanizadas. Foco no manejo multidimensional da dor, melhorando qualidade de vida e funcionalidade.",
    benefits: [
      "Redução significativa dos níveis de dor",
      "Melhora da qualidade do sono",
      "Aumento da capacidade funcional",
      "Redução da fadiga crônica",
      "Melhora do bem-estar emocional",
      "Estratégias de autogerenciamento da dor",
    ],
    techniques: [
      "Educação em neurociência da dor",
      "Exercícios terapêuticos graduados",
      "Liberação miofascial",
      "Auriculoterapia",
      "Ventosaterapia",
      "Técnicas de relaxamento e respiração",
      "Terapia cognitivo-comportamental aplicada",
    ],
    idealFor: [
      "Fibromialgia",
      "Dor crônica generalizada",
      "Síndrome da fadiga crônica",
      "Dor miofascial",
      "Dor neuropática",
      "Síndrome de dor regional complexa",
    ],
    duration: "60 minutos por sessão",
    color: "from-[#ec4899] to-[#db2777]",
  },
  {
    id: "performance-atletica",
    icon: "Trophy",
    title: "Performance Atlética",
    shortDescription: "Treinamento funcional e prevenção de lesões para atletas de alto rendimento.",
    fullDescription:
      "Curso de Fisioterapia no Alto Rendimento pela FAECH (2024) e Fundamentos do Treinamento Esportivo pelo Instituto Olímpico Brasileiro (2025). Especialização em otimização de performance, prevenção de lesões e recuperação atlética. Trabalho focado em atletas de CrossFit, musculação, corrida e esportes de alto impacto.",
    benefits: [
      "Otimização do desempenho atlético",
      "Prevenção de lesões esportivas",
      "Recuperação acelerada entre treinos",
      "Melhora da força e potência muscular",
      "Aprimoramento da mobilidade funcional",
      "Correção de desequilíbrios musculares",
    ],
    techniques: [
      "Avaliação funcional do movimento (FMS)",
      "Treinamento de força funcional",
      "Exercícios pliométricos",
      "Treino de estabilidade e core",
      "Mobilidade articular dinâmica",
      "Periodização do treinamento",
    ],
    idealFor: [
      "Atletas de alto rendimento",
      "Praticantes de CrossFit",
      "Corredores de longa distância",
      "Lutadores e atletas de combate",
      "Jogadores de futebol, vôlei, basquete",
      "Atletas em preparação para competições",
    ],
    duration: "60 minutos por sessão",
    color: "from-[#d4af37] to-[#e8c547]",
  },
  {
    id: "pilates-classico-adaptado",
    icon: "Circle",
    title: "Pilates Clássico Adaptado ao Paciente",
    shortDescription: "Método Pilates clássico personalizado às necessidades individuais de cada paciente para reeducação postural, alívio da dor e ganho funcional.",
    fullDescription:
      "Curso de Pilates Clássico Adaptado pelo Instituto Meta (2025). Aplicação fidedigna do método original de Joseph H. Pilates, porém com seleção e progressão de exercícios planejadas de acordo com a avaliação funcional, limitações e objetivos de cada paciente. Trabalha controle motor, respiração, força do core, mobilidade articular e consciência corporal, sendo indicado tanto na fase aguda quanto na manutenção de diversas condições clínicas.",
    benefits: [
      "Reeducação postural global e alinhamento corporal",
      "Fortalecimento do core e da musculatura estabilizadora",
      "Alívio e prevenção de dores lombares, cervicais e articulares",
      "Melhora do equilíbrio, coordenação e propriocepção",
      "Aumento da capacidade respiratória e redução do estresse",
      "Retorno funcional seguro após lesões ou cirurgias",
    ],
    techniques: [
      "Exercícios clássicos solo (mat) com adaptações individuais",
      "Uso de acessóros: magic circle, theraband, bola suíça, foam roller",
      "Sequências de mobilização da coluna (rolamento, cat-camel, etc.)",
      "Exercícios de estabilização escapular e pélvica",
      "Integração respiratória diafragmática com movimento",
      "Progressão gradual baseada em sinais clínicos e objetivos",
    ],
    idealFor: [
      "Pacientes com dores crônicas lombares ou cervicais",
      "Pós-operatório de cirurgias ortopédicas (coluna, quadril, ombro)",
      "Gestantes e puérperas com adaptações específicas",
      "Idosos buscando equilíbrio, força e prevenção de quedas",
      "Indivíduos com escoliose, hipercifose ou hiperlordose",
      "Atletas em reabilitação ou na transição para treino funcional",
      "Sedentários iniciando atividade física com segurança",
    ],
    duration: "45-50 minutos por sessão",
    color: "from-[#ef4444] to-[#dc2626]"
  },
]

export function getServiceById(id: string): Service | undefined {
  return servicesData.find((service) => service.id === id)
}

export function getServicesByCategory(category: string): Service[] {
  // You can implement category filtering if needed
  return servicesData
}
